# Generated by Django 5.2.9 on 2025-12-30 21:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price_cop', models.PositiveIntegerField()),
                ('billing_unit', models.CharField(choices=[('MINUTES', 'Minutes'), ('HOUR', 'Hour'), ('DAY', 'Day')], default='HOUR', max_length=10)),
                ('unit_size', models.PositiveIntegerField(default=60)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=12)),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('total_amount_cop', models.PositiveIntegerField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.rateplan')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.vehicletype')),
            ],
        ),
        migrations.AddField(
            model_name='rateplan',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='parking.vehicletype'),
        ),
        migrations.AlterUniqueTogether(
            name='rateplan',
            unique_together={('name', 'vehicle_type')},
        ),
    ]
