# Generated by Django 5.2.9 on 2026-01-06 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_clienttype_remove_ticket_closed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito (Empresa)')], max_length=10)),
                ('status', models.CharField(choices=[('PAID', 'Pagado'), ('PENDING', 'Pendiente')], default='PAID', max_length=10)),
                ('transfer_ref', models.CharField(blank=True, max_length=80, null=True, verbose_name='Referencia/Transacción')),
                ('amount_cop', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parking.company')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='parking.ticket')),
            ],
        ),
    ]
