# Generated by Django 5.2.9 on 2026-01-06 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_company_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parking.company'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parking.clienttype'),
            preserve_default=False,
        ),
    ]
