# Generated by Django 5.2.9 on 2026-01-09 02:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_ticket_closed_by_ticket_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=30, unique=True, verbose_name='Cédula o NIT')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nombres y apellidos / Razón social')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('is_company', models.BooleanField(default=False, verbose_name='Habilitada para crédito (empresa)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Pago de empresas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_as_customer', to='parking.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_as_company', to='parking.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_as_company', to='parking.customer'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
