# Generated by Django 5.2.9 on 2026-01-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_customer_payment_invoice_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='work_amount_cop',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_type',
            field=models.CharField(choices=[('NONE', 'Ninguno'), ('EMBARILLADO', 'Embarillado'), ('DESEMBARILLADO', 'Des-embarillado'), ('ENCARPADO', 'Encarpado'), ('OTHER', 'Otros')], default='NONE', max_length=20),
        ),
    ]
