# Generated by Django 5.2.9 on 2026-01-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_ticket_work_amount_cop_ticket_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='service_amount_cop',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(default='NONE', max_length=80),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='ACTIVE', max_length=10),
        ),
    ]
