# Generated by Django 5.2.9 on 2026-01-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_closure_ticket_closure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateplan',
            name='billing_unit',
        ),
        migrations.RemoveField(
            model_name='rateplan',
            name='unit_size',
        ),
    ]
