# Generated by Django 5.2.9 on 2026-01-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_remove_rateplan_billing_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_kind',
            field=models.CharField(blank=True, choices=[('PARKING', 'Parqueadero'), ('WORKSHOP', 'Taller')], db_index=True, max_length=12, null=True),
        ),
    ]
