# Generated by Django 5.2.9 on 2026-01-13 06:34

from django.db import migrations


def forwards(apps, schema_editor):
    Ticket = apps.get_model("parking", "Ticket")

    # Recorremos solo los que NO tienen client_kind aún
    qs = Ticket.objects.filter(client_kind__isnull=True)

    for t in qs.iterator():
        kind = None

        # Intentar derivar desde el FK legado client_type.name
        try:
            legacy_name = (t.client_type.name or "").strip().lower()
        except Exception:
            legacy_name = ""

        if "taller" in legacy_name:
            kind = "WORKSHOP"
        else:
            kind = "PARKING"

        # Guardar
        Ticket.objects.filter(pk=t.pk).update(client_kind=kind)


def backwards(apps, schema_editor):
    Ticket = apps.get_model("parking", "Ticket")
    # Reversa simple: dejarlo en null
    Ticket.objects.all().update(client_kind=None)


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0010_ticket_client_kind"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
