# Generated by Django 5.2.9 on 2026-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_migrate_clienttype_to_clientkind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client_type',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_kind',
            field=models.CharField(choices=[('PARKING', 'Parqueadero'), ('WORKSHOP', 'Taller')], db_index=True, default='PARKING', max_length=12),
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
    ]
