# Generated by Django 5.2.9 on 2026-01-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_remove_ticket_client_type_alter_ticket_client_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rateplan',
            options={'ordering': ('vehicle_type__name', 'client_kind', 'billing_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='rateplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='billing_unit',
            field=models.CharField(blank=True, choices=[('HOUR', 'Hora / Fracción'), ('NIGHT', 'Noche')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='client_kind',
            field=models.CharField(blank=True, choices=[('PARKING', 'Parqueadero'), ('WORKSHOP', 'Taller')], db_index=True, default='PARKING', max_length=12, null=True),
        ),
        migrations.RemoveField(
            model_name='rateplan',
            name='name',
        ),
    ]
