# Generated by Django 5.2.9 on 2026-01-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_auto_20260113_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateplan',
            name='billing_unit',
            field=models.CharField(choices=[('HOUR', 'Hora / Fracción'), ('NIGHT', 'Noche')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='client_kind',
            field=models.CharField(choices=[('PARKING', 'Parqueadero'), ('WORKSHOP', 'Taller')], db_index=True, default='PARKING', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='rateplan',
            unique_together={('vehicle_type', 'client_kind', 'billing_unit')},
        ),
    ]
