# Generated by Django 5.2.9 on 2026-01-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_alter_rateplan_billing_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closure',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin del Periodo'),
        ),
        migrations.AddField(
            model_name='closure',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio del Periodo'),
        ),
    ]
