# Generated by Django 5.2.9 on 2026-01-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_closure_period_end_closure_period_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rateplan',
            options={'ordering': ('vehicle_type__name', 'client_kind', 'billing_unit', 'day_type')},
        ),
        migrations.AlterUniqueTogether(
            name='rateplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='day_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SUNDAY', 'Domingo'), ('HOLIDAY', 'Festivo')], db_index=True, default='NORMAL', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='rateplan',
            unique_together={('vehicle_type', 'client_kind', 'billing_unit', 'day_type')},
        ),
    ]
