# Generated by Django 5.2.9 on 2026-01-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_alter_rateplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_enabled',
            field=models.BooleanField(default=False, verbose_name='Crédito habilitado (acumulable)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Es empresa'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ASSIGNED', 'Assigned'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='ACTIVE', max_length=10),
        ),
    ]
