# Generated by Django 5.2.9 on 2026-01-26 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0018_customer_credit_enabled_alter_customer_is_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_parking_cop',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_service_cop',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='tickets_payload',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='parking.ticket'),
        ),
    ]
