# Generated by Django 5.2.9 on 2026-01-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_payment_amount_parking_cop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
