# Generated by Django 5.2.9 on 2026-02-08 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0020_monthlyplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicInvoiceOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(db_index=True, max_length=30, verbose_name='Cédula o NIT')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nombre o razón social')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('total_amount_cop', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviada')], db_index=True, default='PENDING', max_length=10)),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Último error')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Último intento')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='parking_ele_status_1263e5_idx'), models.Index(fields=['id_number'], name='parking_ele_id_numb_2eaf08_idx')],
            },
        ),
    ]
