# Generated by Django 5.2.9 on 2026-02-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0021_electronicinvoiceoutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicinvoiceoutbox',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='electronicinvoiceoutbox',
            name='items_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='electronicinvoiceoutbox',
            index=models.Index(fields=['items_hash'], name='parking_ele_items_h_d8fbd0_idx'),
        ),
    ]
