# Generated by Django 5.2.9 on 2026-02-16 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0022_electronicinvoiceoutbox_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.TimeField(default=datetime.time(6, 0), verbose_name='Inicio Jornada Día')),
                ('night_start', models.TimeField(default=datetime.time(18, 0), verbose_name='Inicio Jornada Noche')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='client_kind',
            field=models.CharField(choices=[('PARKING', 'Parqueadero'), ('WORKSHOP', 'Taller'), ('SERVICE', 'Servicio')], db_index=True, default='PARKING', max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_kind',
            field=models.CharField(choices=[('PARKING', 'Parqueadero'), ('WORKSHOP', 'Taller'), ('SERVICE', 'Servicio')], db_index=True, default='PARKING', max_length=12),
        ),
    ]
