# Generated by Django 5.2.9 on 2026-02-16 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0023_systemsettings_alter_rateplan_client_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WorkType',
                'verbose_name_plural': 'WorkType',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Time Window', 'verbose_name_plural': 'Time Window'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='work_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_type_code',
            field=models.CharField(db_index=True, default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='parking.worktype'),
        ),
    ]
