# Generated by Django 5.2.9 on 2026-02-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0025_fill_work_type_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='work_type_fk',
            new_name='work_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='work_type_code',
        ),
    ]
