# Generated by Django 5.2.9 on 2026-02-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0026_rename_work_type_fk_ticket_work_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='work_type',
            new_name='work_type_fk',
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_type_text',
            field=models.CharField(blank=True, default='NONE', max_length=40),
        ),
    ]
