# Generated by Django 5.2.9 on 2026-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0027_rename_work_type_ticket_work_type_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del negocio')),
                ('owner_name', models.CharField(blank=True, max_length=150, verbose_name='Propietario')),
                ('nit', models.CharField(max_length=30, verbose_name='NIT')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información del Negocio',
                'verbose_name_plural': 'Información del Negocio',
            },
        ),
    ]
