# Generated by Django 5.2.9 on 2026-02-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0028_businessinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVehiclesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consecutive', models.PositiveIntegerField(unique=True)),
                ('active_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'verbose_name': 'BusinessInfo', 'verbose_name_plural': 'BusinessInfo'},
        ),
    ]
