# Generated by Django 5.2.9 on 2026-02-17 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0030_monthlyreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consecutive', models.PositiveIntegerField(unique=True)),
                ('total_amount_cop', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.PROTECT, related_name='company_receipts', to='parking.customer')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_receipt', to='parking.payment')),
            ],
        ),
    ]
