# Generated by Django 5.2.9 on 2026-02-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0031_companyreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReceiptNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consecutive', models.PositiveIntegerField(unique=True)),
                ('amount_cop', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyReceipt',
        ),
    ]
