# Generated by Django 5.2.9 on 2026-02-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0032_companyreceiptnumber_delete_companyreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha festiva')),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre/nota')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Festivo',
                'verbose_name_plural': 'Festivos',
                'ordering': ('-date',),
            },
        ),
    ]
