# Generated by Django 5.2.9 on 2026-02-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0033_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ('-date',), 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holiday'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='allow_manual_total',
            field=models.BooleanField(default=False, help_text='Si está activo, permite editar manualmente el total en el admin (no se recalcula automáticamente desde el admin).'),
        ),
    ]
