# Generated by Django 5.2.9 on 2026-02-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0034_alter_holiday_options_ticket_allow_manual_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicinvoiceoutbox',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ERROR', 'Error'), ('SENT', 'Enviada')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
