# Generated by Django 5.2.9 on 2026-02-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0035_alter_electronicinvoiceoutbox_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='electronicinvoiceoutbox',
            name='parking_ele_status_1263e5_idx',
        ),
        migrations.AddField(
            model_name='electronicinvoiceoutbox',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviada el'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoiceoutbox',
            index=models.Index(fields=['status', 'created_at'], name='parking_ele_status_db2634_idx'),
        ),
    ]
