# Generated by Django 5.2.9 on 2026-02-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0036_remove_electronicinvoiceoutbox_parking_ele_status_1263e5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
